### PR TITLE
#10 Added swagger yaml to document the API

### PR DESCRIPTION
**Pull request by shubhamofbce**
This Merge request is for Issue #10 
- [x]  Add Document for Auth Routes
- [x]  Add Document for Admin Auth Routes
- [x] Add Document for User Routes
- [x] Add Schemas for all the models

### CODE REVIEW

**Comment by shubhamofbce** [comment]
Hi @fayaz07 and @prudhvir3ddy  , Please review the changes till now, I am still working on it.  
I think the tests are failing as the sendgrid API key is missing in the pipeline env as I got this error message from the pipeline. If there is something wrong from my side then you can point out.
``` 
Error: Sendgrid API Key is not specified. Please specify the API key in your environment variables, as SENDGRID_API_KEY=<your-api-key-here>
npm ERR! Test failed.  See above for more details.
```

**Comment by fayaz07** [comment]
Hi @shubhamofbce that might be a case if you haven't added repo secrets, which will include config of `.env`

**Comment by shubhamofbce** [comment]
Hi @fayaz07 Can u please help me understand  what is this repo secret as I am unable to figure it out.  
I have set all the values in my .env file in my local machine.

**Comment by fayaz07** [comment]
Hi @shubhamofbce , repo secrets are nothing but the key value properties in `.env` file. Just copy them whole, create a new property in repo secrets(look for the key in github workflow, I guess it would be ENV_VARS_LOCALHOST) 

This is because, we will not expose our original env variables in our repo, so in order to run the actions we need the env variables, so for gh actions we will pull the secrets and push them into a `.env` file which will be just used for running the gh actions.

**Comment by shubhamofbce** [comment]
@fayaz07 I tried the same as u suggested, created a secret with  ENV_VARS_LOCALHOST and pasted the whole .env data in value. But still I am getting the same issue.  
I checked for the name in workflow also it is same as ENV_VARS_LOCALHOST.

**Comment by fayaz07** [comment]
Hi @shubhamofbce , there is no issue with gh actions, I have just checked in a new test branch, for more info check [this](https://github.com/stackinflow/node-rest-api-starter/actions/runs/239278223). Did you fill all the values in the .env which you pasted in gh secrets.

**Comment by shubhamofbce** [comment]
image
Updated screenshot

**Pull request merged**
